print ("About the Scratch archive RAM requirement system")
print ("The Scratch archive's RAM requirement system is based off the Scratch 2 specs for projects that require less than 128 Megabytes of RAM to run on Scratch 2, and projects above that are based off Scratch 3")
print ("The minimum RAM requirement is 32 Megabytes. This rating applies mostly to projects that are a still image, slideshow with no effects, or just music/sound effects")
print ("This rating can also be 48 Megabytes or 64 Megabytes depending on the graphical level of the projects")
print ("Projects that require 96 or 128 Megabytes of RAM are lightweight projects that can run on Scratch 2")
print ("Since projects over 128 Megabytes are based off Scratch 3's requirements, there is currently no Scratch 2 documentation for them."(
print ("Projects like these increase their requirement due to how many processes are running in the project, and how many sprites are in use.")
print ("Most operating system projects require between 128 Megabytes and 256 Megabytes for early builds, but normally go no higher than 2048 Megabytes (2.04 Gigabytes) or 4096 Megabytes (4.09 Gigabytes)")
print ("There is only 1 project that requires 6 gigabytes of RAM due to its heavy usage of sprites. It is an older Turkey game")
print ("To stay safe, any project will be able to run with 8 gigabytes of RAM. The rating helps you determine how much memory it will use, so that you can use it on legacy virtual machines")
noMore = input("Press [ENTER] key to exit")