print ("About the Scratch archive age rating system")
print ("The scratch archive age rating system is based off the following factors:")
print ("* Language used")
print ("* Project navigation difficulty")
print ("* Recommended age")
print ("* Graphics")
print ("* Project topic")
print ("For example, the 0+ and 3+ ratings are meant for projects with little to no interaction. Most of these consist of sound effects, and music only projects")
print ("The 5+ rating applies for the majority of projects. Commonly, the operating systems have a 5+ rating. Some have a 6+ rating, but no higher")
print ("Most games consist of the 5+ rating. Based on the project topic, it can vary")
print ("The 7+ and 8+ rating are for projects that require some skill, and have topics that 0-6 year olds don't have a full grasp on normally.")
print ("Projects with a 9+ or 10+ age rating are for more difficult topics.")
print ("Projects with a 12+ or 13+ rating are projects that aren't entirely family friendly, and should be used carefully")
print ("Projects with the 17+ or 18+ rating are meme projects that Scratch took down. This was before I was aware of the terms of service. These projects can be viewed by any age if the user doesn't repeat it, or get offended by it.")
print ("Less than 1% of all projects are 17+ or 18+ and should be avoided by immature children")
print ("The projects are designed for almost all ages. These age ratings are not completely accurate, but are still 99% accurate and trustable.")
noMore = input("Press [ENTER] key to exit")