print ("My scratch projects")
print ("from scratch.mit.edu")
print ("\n1336 items")
print ("0001 | seans epic trivia 5 trivia type challenge       |")
print ("0002 | The maze                                        |")
print ("0003 | Sean and mitchells puppy paradise movie         |")
print ("0004 | Meme's first scratch                            |")
print ("0005 | immortal combat dragon version                  |")
print ("0006 | Halloween                                       |")
print ("0007 | Super Scratch Pong 2                            |")
print ("0008 | Defend the planet                               |")
print ("0009 | Archer I                                        |")
print ("0010 | TRM Quiz                                        |")
print ("0011 | Castle Siege Scratch                            |")
print ("0012 | Grand Theft Auto - scratch                      |")
print ("0013 | The lab \"rat\"                                   |")
print ("0014 | White house down                                |")
print ("0015 | Crossy scratch                                  |")
print ("0016 | I like trains scratch edition                   |")
print ("0017 | Five nights at scratch                          |")
print ("0018 | NASA scratch                                    |")
print ("0019 | Multiplication tables with scratch cat          |")
print ("0020 | Bounce Party!!!!!!!!!!!!!!!!!!!!!!!!!!!         |")
print ("0021 | Gold rush                                       |")
print ("0022 | Turkey Nightmare IV                             |")
print ("0023 | Turkey simulator                                |")
print ("0024 | Dodge The Bullet -Turkey edition                |")
print ("0025 | Don't shoot the turkey                          |")
print ("0026 | Turkey stuffing                                 |")
print ("0027 | Si high demo                                    |")
print ("0028 | Dumb ways to scratch                            |")
print ("0029 | Girl Game I                                     |")
print ("0030 | Escape the prison - scratch                     |")
print ("0031 | War survival                                    |")
print ("0032 | Rayco.com                                       |")
print ("0033 | Super scratch pong 2015                         |")
print ("0034 | Ancient warfare I                               |")
print ("0035 | Job career test                                 |")
print ("0036 | Unlucky buttons                                 |")
more1 = input("View 50 more [ENTER]")
print ("0037 | Nuclear cat roadmine                            |")
print ("0038 | Uncle Unicapricornicopria                       |")
print ("0039 | Neon scratch                                    |")
print ("0040 | Lol cat                                         |")
print ("0041 | Nauseator                                       |")
print ("0042 | Instruments                                     |")
print ("0043 | The sounds of scratch                           |")
print ("0044 | None direction band                             |")
print ("0045 | Die hard                                        |")
print ("0046 | Bomb simulator                                  |")
print ("0047 | Are you like Sean quiz                          |")
print ("0048 | Swift cat                                       |")
print ("0049 | Most MLG scratch pro ever                       |")
print ("0050 | Five nights at scratch 2                        |")
print ("0051 | Super scratch                                   |")
print ("0052 | Space story                                     |")
print ("0053 | Plants vs. scratchies                           |")
print ("0054 | Turkey cooking                                  |")
print ("0055 | Space quest                                     |")
print ("0056 | Island survival                                 |")
print ("0057 | Untitled                                        |")
print ("0058 | Super scratch 2                                 |")
print ("0059 | Survival maximum                                |")
print ("0060 | MLG Halloween 2015                              |")
print ("0061 | Most MLG scratch project ever 2                 |")
print ("0062 | A day at the beach                              |")
print ("0063 | War of control                                  |")
print ("0064 | Game development studio                         |")
print ("0065 | Land of knowledge                               |")
print ("0066 | Island survival 2 the lost realm                |")
print ("0067 | Game studio                                     |")
print ("0068 | Casino story copy                               |")
print ("0069 | Farmpro premium                                 |")
print ("0070 | Derp                                            |")
print ("0071 | Untitled-2                                      |")
print ("0072 | Siege premium                                   |")
print ("0073 | Untitled-3                                      |")
print ("0074 | Fredbears pizza                                 |")
print ("0075 | Scratch explorer                                |")
print ("0076 | Castle story copy                               |")
print ("0077 | Scratch race                                    |")
print ("0078 | Turkey                                          |")
print ("0079 | Untitled-4                                      |")
print ("0080 | Untitled-5                                      |")
print ("0081 | MLG                                             |")
print ("0082 | Turkey run                                      |")
print ("0083 | Untitled-6                                      |")
print ("0084 | Scratch party                                   |")
print ("0085 | Castle story                                    |")
print ("0086 | Crossy scratch                                  |")
more1 = input("View 50 more [ENTER]")
print ("0087 |")
print ("0088 |")
print ("0089 |")
print ("0090 |")
print ("0091 |")
print ("0092 |")
print ("0093 |")
print ("0094 |")
print ("0095 |")
print ("0096 |")
print ("0097 |")
print ("0098 |")
print ("0099 |")
print ("0100 |")
search1 = str(input("Search a project before you leave? type a number 1 through 1336 or type 'about'"))
if (search1 == "1"):
	print ("seans epic trivia 5 trivia type challenge")
	print ("Sean's very first scratch project")
if (search1 == "about" or search1 == "About" or search1 == "ABOUT" or search1 == "aBOUT"):
	print ("About")
	print ("This is a python based directory containing info for all scratch projects hosted on Sean's main scratch account")
noMore = input("Those are all of Sean's scratch projects\nPress [ENTER] key to exit")
# Version 1.1
# January 15th 2019 build