print ("My scratch projects")
print ("from scratch.mit.edu")
print ("\n1336 items")
print ("0001 | seans epic trivia 5 trivia type challenge       |")
print ("0002 | The maze                                        |")
print ("0003 | Sean and mitchells puppy paradise movie         |")
print ("0004 | Meme's first scratch                            |")
print ("0005 | immortal combat dragon version                  |")
print ("0006 | Halloween                                       |")
print ("0007 | Super Scratch Pong 2                            |")
print ("0008 | Defend the planet                               |")
print ("0009 | Archer I                                        |")
print ("0010 | TRM Quiz                                        |")
print ("0011 | Castle Siege Scratch                            |")
print ("0012 | Grand Theft Auto - scratch                      |")
print ("0013 | The lab \"rat\"                                   |")
print ("0014 | White house down                                |")
print ("0015 | Crossy scratch                                  |")
print ("0016 | I like trains scratch edition                   |")
print ("0017 | Five nights at scratch                          |")
print ("0018 | NASA scratch                                    |")
print ("0019 | Multiplication tables with scratch cat          |")
print ("0020 | Bounce Party!!!!!!!!!!!!!!!!!!!!!!!!!!!         |")
print ("0021 | Gold rush                                       |")
print ("0022 | Turkey Nightmare IV                             |")
print ("0023 | Turkey simulator                                |")
print ("0024 | Dodge The Bullet -Turkey edition                |")
print ("0025 | Don't shoot the turkey                          |")
print ("0026 | Turkey stuffing                                 |")
print ("0027 | Si high demo                                    |")
print ("0028 | Dumb ways to scratch                            |")
print ("0029 | Girl Game I                                     |")
print ("0030 | Escape the prison - scratch                     |")
print ("0031 | War survival                                    |")
print ("0032 | Rayco.com                                       |")
print ("0033 | Super scratch pong 2015                         |")
print ("0034 | Ancient warfare I                               |")
print ("0035 | Job career test                                 |")
print ("0036 | Unlucky buttons                                 |")
more1 = input("View 50 more [ENTER]")
print ("0037 |")
print ("0038 |")
print ("0039 |")
print ("0040 |")
print ("0041 |")
print ("0042 |")
noMore = input("Those are all of Sean's scratch projects\nPress [ENTER] key to exit")
# Version 1.0 
# January 14th 2019 build